services:
  api:
    container_name: ansible-manager-api
    restart: unless-stopped
    build:
      context: ./api
    ports:
      - 8080:8080
    environment:
      - MONGODB_URL=mongodb://ansible-manager-db:27017
      - SECRET_KEY=secret
    volumes:
      - /DATA/AppData/ansible-manager/logs:/logs
      - /DATA/AppData/ansible-manager/cron.d:/etc/cron.d
      - /DATA/AppData/ansible-manager/ansible-playbooks:/ansible-playbooks
      - /DATA/AppData/ansible-manager/config:/config

  ui:
    container_name: ansible-manager-ui
    restart: unless-stopped
    build:
      context: ./ui
    ports:
      - '3000:3000'

  database:
    image: mongo:latest
    container_name: ansible-manager-db
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - database_data:/database/data

volumes:
  database_data:
    driver: local