version: '3.8'
services:
  api:
    container_name: ansible-manager-api
    restart: unless-stopped
    build:
      context: ./api
    ports:
      - '8080:8080'
    volumes:
      - /home/ansible/logs:/logs
      - /var/spool/cron/crontabs:/crontabs
      - /home/ansible/ansible-playbooks:/ansible-playbooks

  ui:
    container_name: ansible-manager-ui
    restart: unless-stopped
    build:
      context: ./ui
    ports:
      - '3000:3000'