version: '3.8'
services:
  api:
    container_name: ansible-manager-api
    restart: unless-stopped
    build:
      context: ./api
    ports:
      - 8080:8080
    volumes:
      - /DATA/AppData/ansible-manager/logs:/logs
      - /DATA/AppData/ansible-manager/cron.d:/etc/cron.d
      - /DATA/AppData/ansible-manager/ansible-playbooks:/ansible-playbooks
      - /DATA/AppData/ansible-manager/config:/config
    environment:
      - ANSIBLE_INVENTORY=/ansible-playbooks/inventories/hosts.yaml
      - ANSIBLE_PLAYBOOKS=/ansible-playbooks/playbooks
      - ANSIBLE_SCRIPTS=/ansible-playbooks/scripts
      - ANSIBLE_LOGS=/logs
      - VAULT_PASSWORD_FILE=/config/vault_password_file

  ui:
    container_name: ansible-manager-ui
    restart: unless-stopped
    build:
      context: ./ui
    ports:
      - '3000:3000'