FROM node:18-alpine

LABEL org.opencontainers.image.source = "https://github.com/r-dvl/ansible-manager"
LABEL org.opencontainers.image.description "Ansible Dashboard"

# React ENV Vars
ARG API_URL
ENV REACT_APP_API_URL $API_URL

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

EXPOSE 3000

RUN npm install serve -g

CMD ["serve", "-s", "dist"]