FROM node:18-alpine

LABEL org.opencontainers.image.source = "https://github.com/r-dvl/ansible-manager"
LABEL org.opencontainers.image.description "Ansible Dashboard"

# Env vars
ENV TZ=Europe/Madrid

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build:demo

EXPOSE 3000

RUN npm install serve -g

COPY ./start.sh /start.sh

CMD ["/bin/bash", "/start.sh"]