FROM python:3.10

LABEL org.opencontainers.image.source="https://github.com/r-dvl/ansible-manager"
LABEL org.opencontainers.image.description="Ansible Manager API"

# Setup
WORKDIR /api
ENV TZ=Europe/Madrid

# Install dependencies
COPY ./requirements.txt /api/requirements.txt

# Install Ansible and cron
RUN apt-get update && apt-get install -y sshpass cron tzdata && \
    pip install --no-cache-dir --upgrade -r /api/requirements.txt && \
    pip install ansible

# Copy code
COPY ./main.py /api
COPY ./v1 /api/v1

# Copy startup script
COPY ./start.sh /start.sh

# Ensure the start.sh script is executable
RUN chmod +x /start.sh

# API listener port
EXPOSE 8080

# Start the application using the start.sh script
CMD ["/bin/bash", "/start.sh"]